# -*- coding: utf-8 -*-
"""3d-printer-defect-detection-ram-fixed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h-TtxSBvEHeLdR52-FEKyIhCPTUHLgyF

#### ref: https://www.tensorflow.org/tutorials/
"""

import matplotlib.pyplot as plt
import numpy as np
import PIL
import os

import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

"""### load data"""

import kagglehub

# Download dataset and get path
data_dir = kagglehub.dataset_download("arunrk7/surface-crack-detection")

print("Path to dataset files:", data_dir)

batch_size = 16
img_height = 128
img_width = 128

train_ds = tf.keras.utils.image_dataset_from_directory(
  directory = data_dir,
  validation_split=0.2,
  subset="training",
  seed=123,
  image_size=(img_height, img_width),
  batch_size=batch_size)

val_ds = tf.keras.utils.image_dataset_from_directory(
  directory = data_dir,
  validation_split=0.2,
  subset="validation",
  seed=123,
  image_size=(img_height, img_width),
  batch_size=batch_size)

class_names = train_ds.class_names
print(class_names)

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 10))
for images, labels in train_ds.take(1):
  for i in range(9):
    ax = plt.subplot(3, 3, i + 1)
    plt.imshow(images[i].numpy().astype("uint8"))
    plt.title(class_names[labels[i]])
    plt.axis("off")

for image_batch, labels_batch in train_ds:
  print(image_batch.shape)
  print(labels_batch.shape)
  break

AUTOTUNE = tf.data.AUTOTUNE

# Removed .cache() — it loads entire dataset into RAM (causes OOM on 12GB)
# Reduced shuffle buffer from 1000 to 200 to save memory
train_ds = train_ds.shuffle(200).prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.prefetch(buffer_size=AUTOTUNE)

normalization_layer = layers.Rescaling(1./255)

normalized_ds = train_ds.map(lambda x, y: (normalization_layer(x), y))
image_batch, labels_batch = next(iter(normalized_ds))
first_image = image_batch[0]
# Notice the pixel values are now in `[0,1]`.
print(np.min(first_image), np.max(first_image))

"""## Basic Model 1"""

num_classes = len(class_names)

model = Sequential([
  layers.Rescaling(1./255, input_shape=(img_height, img_width, 3)),
  layers.Conv2D(16, 3, padding='same', activation='relu'),
  layers.MaxPooling2D(),
  layers.Conv2D(32, 3, padding='same', activation='relu'),
  layers.MaxPooling2D(),
  layers.Conv2D(64, 3, padding='same', activation='relu'),
  layers.MaxPooling2D(),
  layers.Flatten(),
  layers.Dense(128, activation='relu'),
  layers.Dense(num_classes)
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.summary()

epochs = 10  # reduced from 15
history = model.fit(
  train_ds,
  validation_data=val_ds,
  epochs=epochs
)

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

loss = history.history['loss']
val_loss = history.history['val_loss']

epochs_range = range(epochs)

plt.figure(figsize=(8, 8))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

"""### data augmentation"""

data_augmentation = keras.Sequential(
  [
    layers.RandomFlip("horizontal",
                      input_shape=(img_height,
                                  img_width,
                                  3)),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1),
  ]
)

plt.figure(figsize=(10, 10))
for images, _ in train_ds.take(1):
  for i in range(9):
    augmented_images = data_augmentation(images)
    ax = plt.subplot(3, 3, i + 1)
    plt.imshow(augmented_images[0].numpy().astype("uint8"))
    plt.axis("off")

"""## Model 2"""

model = Sequential([
  data_augmentation,
  layers.Rescaling(1./255),
  layers.Conv2D(16, 3, padding='same', activation='relu'),
  layers.MaxPooling2D(),
  layers.Conv2D(32, 3, padding='same', activation='relu'),
  layers.MaxPooling2D(),
  layers.Conv2D(64, 3, padding='same', activation='relu'),
  layers.MaxPooling2D(),
  layers.Dropout(0.2),
  layers.Flatten(),
  layers.Dense(128, activation='relu'),
  layers.Dense(num_classes, name="outputs")
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.summary()

epochs = 5
history = model.fit(
  train_ds,
  validation_data=val_ds,
  epochs=epochs
)

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

loss = history.history['loss']
val_loss = history.history['val_loss']

epochs_range = range(epochs)

plt.figure(figsize=(8, 8))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

model.save("crack_detector_model.keras")

pip install streamlit tensorflow pillow numpy

import streamlit as st
import tensorflow as tf
from PIL import Image
import numpy as np

# Set page configuration
st.set_page_config(page_title="3D Print Crack Detector", layout="centered")

st.title("🔍 3D Printer Defect Detection")
st.write("Upload a photo of a 3D print to check for surface cracks.")

# 1. Load the trained model
# Ensure 'crack_detector_model.keras' is in the same directory as this script
@st.cache_resource
def load_model():
    return tf.keras.models.load_model("crack_detector_model.keras")

try:
    model = load_model()
    class_names = ['Negative', 'Positive'] # Based on your notebook
except Exception as e:
    st.error(f"Error loading model: {e}")
    st.stop()

# 2. Image Uploading
uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Display the uploaded image
    image = Image.open(uploaded_file)
    st.image(image, caption='Uploaded Image', use_container_width=True)

    st.write("---")

    # 3. Preprocessing (Matching notebook specs: 128x128)
    img_height, img_width = 128, 128

    # Convert image to RGB if it isn't already
    if image.mode != "RGB":
        image = image.convert("RGB")

    img_resized = image.resize((img_height, img_width))
    img_array = tf.keras.utils.img_to_array(img_resized)
    img_array = tf.expand_dims(img_array, 0) # Create a batch

    # 4. Prediction
    if st.button('Predict'):
        with st.spinner('Analyzing surface...'):
            predictions = model.predict(img_array)
            score = tf.nn.softmax(predictions[0])

            result = class_names[np.argmax(score)]
            confidence = 100 * np.max(score)

            # 5. Display Results
            if result == "Positive":
                st.error(f"Crack Detected! (Confidence: {confidence:.2f}%)")
            else:
                st.success(f"No Crack Detected (Confidence: {confidence:.2f}%)")

!pip install -q streamlit
!npm install -g localtunnel

!pip install -q streamlit pyngrok tensorflow pillow

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import tensorflow as tf
# from PIL import Image
# import numpy as np
# 
# st.title("🔍 3D Printer Crack Detector")
# 
# @st.cache_resource
# def load_model():
#     return tf.keras.models.load_model("crack_detector_model.keras")
# 
# model = load_model()
# class_names = ['Negative', 'Positive']
# 
# uploaded_file = st.file_uploader("Upload a photo", type=["jpg", "png"])
# 
# if uploaded_file:
#     image = Image.open(uploaded_file).convert("RGB")
#     st.image(image, caption='Uploaded Image', use_container_width=True)
# 
#     img_resized = image.resize((128, 128))
#     img_array = tf.keras.utils.img_to_array(img_resized)
#     img_array = tf.expand_dims(img_array, 0)
# 
#     if st.button('Predict'):
#         predictions = model.predict(img_array)
#         score = tf.nn.softmax(predictions[0])
#         result = class_names[np.argmax(score)]
#         st.write(f"Result: **{result}** ({100 * np.max(score):.2f}%)")

import urllib
print("Password/Endpoint IP:", urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip())

import subprocess
import time
from pyngrok import ngrok

# Kill any previous streamlit instances
subprocess.run(["pkill", "-f", "streamlit"], capture_output=True)
time.sleep(1)

# Start Streamlit in background
subprocess.Popen([
    "streamlit", "run", "app.py",
    "--server.port=8501",
    "--server.headless=true",
    "--server.enableCORS=false",
    "--server.enableXsrfProtection=false"
])
time.sleep(3)

# Connect ngrok
ngrok.set_auth_token("3CcHOkxxlrxEasdQGWhzEqtJ8jD_75jiXdU7JyGuCmXVGwCWi")  # <-- paste your token
public_url = ngrok.connect(8501)
print("✅ Open your dashboard at:", public_url)